### ISSUE TITLE
Use with scalelite: error on room creation

### ISSUE THREAD

**Issue by jgribonvald** [sualko/cloud_bbb#179]
**Describe the bug**
The configuration with scalelite (without the /api uri) is working, but when creating a room we can't open a room. See bellow for logs.

**To Reproduce**
1. Go to BBB module
2. Click on "Open room button" (after creating a new room)
3. See nextcloud error

**Expected behavior**
Running a BBB room

**System (please complete the following information):**
 - Browser with version: Firefox-dev 93.0b8 (64 bits) (ubuntu 20.04) - not tested on other browser but should be the same
 - App version 2.0.0
 - Nextcloud version 21.0.4
 - BigBlueButton version 2.3.13
 - Is your BigBlueButton instance working with Greenligh? yes
 - Did you enter your BBB API url and secret? yes
 - BigBlueButton is working with moodle yes
 - BigBlueButton servers are used with scalelite and greenlight as Moodle are configured with scalelite.

**Nextcloud log:**

```
{"reqId":"YU2RJu3uZbJC-Njo-JcvAAAAAIw","level":3,"time":"2021-09-24T08:49:43+00:00","remoteAddr":"::ffff:192.168.4.3","user":"F08001ut","app":"index","method":"GET","url":"/index.php/apps/bbb/b/REX3XkmzxFgrCc9R","message":{"Exception":"Exception","Message":"Can not process create request: https://scaliteURL/bigbluebutton/api/create?name=test&meetingID=REX3XkmzxFgrCc9R&attendeePW=A_CODE&moderatorPW=A_CODE&logoutURL=https%3A%2F%2FnextcloudURL.fr&record=false&moderatorOnlyMessage=Pour%20inviter%20quelqu%27un%20%C3%A0%20la%20r%C3%A9union%2C%20envoyez-lui%20ce%20lien%20%3A%20https%3A%2F%2FnextcloudURL.fr%2Findex.php%2Fapps%2Fbbb%2Fb%2FREX3XkmzxFgrCc9R&allowStartStopRecording=false&guestPolicy=ALWAYS_ACCEPT&meta_endCallbackUrl=https%3A%2F%2FnextcloudURL.fr%2Findex.php%2Fapps%2Fbbb%2Fhook%2Fended%2FREX3XkmzxFgrCc9R%2FyfSfENxumSPKc1LNKM1rIDe45Mo&meta_bbb-recording-ready-url=https%3A%2F%2FnextcloudURL.fr%2Findex.php%2Fapps%2Fbbb%2Fhook%2Frecording%2FREX3XkmzxFgrCc9R%2FyfSfENxumSPKc1LNKM1rIDe45Mo&checksum=26e7a6244c889e368e57aa6253006d6fe419b479","Code":0,"Trace":[{"file":"/var/www/PATH/web/apps/bbb/lib/Controller/JoinController.php","line":129,"function":"createMeeting","class":"OCA\\BigBlueButton\\BigBlueButton\\API","type":"->","args":[{"uid":"REX3XkmzxFgrCc9R","name":"test","attendeePassword":"a_code","moderatorPassword":"a_code","welcome":"","maxParticipants":0,"record":false,"userId":"an_ID","access":"public","password":null,"everyoneIsModerator":false,"requireModerator":false,"shared":false,"moderatorToken":null,"listenOnly":true,"mediaCheck":true,"cleanLayout":false,"id":4,"__class__":"OCA\\BigBlueButton\\Db\\Room"},{"__class__":"OCA\\BigBlueButton\\BigBlueButton\\Presentation"}]},{"file":"/var/www/PATH/web/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"index","class":"OCA\\BigBlueButton\\Controller\\JoinController","type":"->","args":["USER NAME","","",""]},{"file":"/var/www/PATH/web/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\BigBlueButton\\Controller\\JoinController"},"index"]},{"file":"/var/www/PATH/web/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\BigBlueButton\\Controller\\JoinController"},"index"]},{"file":"/var/www/PATH/web/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\BigBlueButton\\Controller\\JoinController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"moderatorToken":"","token":"REX3XkmzxFgrCc9R","_route":"bbb.join.index"}]},{"file":"/var/www/PATH/web/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/bbb/b/REX3XkmzxFgrCc9R"]},{"file":"/var/www/PATH/web/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/PATH/web/apps/bbb/lib/BigBlueButton/API.php","Line":130,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:93.0) Gecko/20100101 Firefox/93.0","version":"21.0.4.1","id":"614d933ba5c1b"}
```

**SCALELITE log:**

```
Started GET "/bigbluebutton/api/create?name=test&meetingID=REX3XkmzxFgrCc9R&attendeePW=A_CODE&moderatorPW=A_CODE&logoutURL=https%3A%2F%2FnextcloudURL.fr&record=false&moderatorOnlyMessage=Pour%20inviter%20quelqu%27un%20%C3%A0%20la%20r%C3%A9union%2C%20envoyez-lui%20ce%20lien%20%3A%20https%3A%2F%2FnextcloudURL%2Findex.php%2Fapps%2Fbbb%2Fb%2FREX3XkmzxFgrCc9R&allowStartStopRecording=false&guestPolicy=ALWAYS_ACCEPT&meta_endCallbackUrl=https%3A%2F%2FnextcloudURL%2Findex.php%2Fapps%2Fbbb%2Fhook%2Fended%2FREX3XkmzxFgrCc9R%2FyfSfENxumSPKc1LNKM1rIDe45Mo&meta_bbb-recording-ready-url=https%3A%2F%2FnextcloudURL.fr%2Findex.php%2Fapps%2Fbbb%2Fhook%2Frecording%2FREX3XkmzxFgrCc9R%2FyfSfENxumSPKc1LNKM1rIDe45Mo&checksum=26e7a6244c889e368e57aa6253006d6fe419b479" for AN IP at 2021-09-24 08:49:43 +0000
I, [2021-09-24T08:49:43.021378 #29]  INFO -- : [7226e315-5e56-4054-926e-6db23b697ec6] Processing by BigBlueButtonApiController#create as XML
I, [2021-09-24T08:49:43.021496 #29]  INFO -- : [7226e315-5e56-4054-926e-6db23b697ec6]   Parameters: {"name"=>"test", "meetingID"=>"REX3XkmzxFgrCc9R", "attendeePW"=>"aG9sijoqtFPYnyGtN5y6xcbaSi32Maeo", "moderatorPW"=>"YEpKXqL82Z8CRLZdGYnjwrZgtPbxEcJD", "logoutURL"=>"https://gip.nextcloud.recia.aquaray.com", "record"=>"false", "moderatorOnlyMessage"=>"Pour inviter quelqu'un à la réunion, envoyez-lui ce lien : https://gip.nextcloud.recia.aquaray.com/index.php/apps/bbb/b/REX3XkmzxFgrCc9R", "allowStartStopRecording"=>"false", "guestPolicy"=>"ALWAYS_ACCEPT", "meta_endCallbackUrl"=>"https://gip.nextcloud.recia.aquaray.com/index.php/apps/bbb/hook/ended/REX3XkmzxFgrCc9R/yfSfENxumSPKc1LNKM1rIDe45Mo", "meta_bbb-recording-ready-url"=>"https://gip.nextcloud.recia.aquaray.com/index.php/apps/bbb/hook/recording/REX3XkmzxFgrCc9R/yfSfENxumSPKc1LNKM1rIDe45Mo", "checksum"=>"26e7a6244c889e368e57aa6253006d6fe419b479"}
I, [2021-09-24T08:49:43.023104 #14]  INFO -- : [cbd25218-d688-4611-a6ee-8456f5c01cc5] Started HEAD "/health_check" for AN IP at 2021-09-24 08:49:43 +0000
I, [2021-09-24T08:49:43.023938 #14]  INFO -- : [cbd25218-d688-4611-a6ee-8456f5c01cc5] Processing by HealthCheckController#all as HTML
D, [2021-09-24T08:49:43.024225 #29] DEBUG -- : [7226e315-5e56-4054-926e-6db23b697ec6] Creating meeting REX3XkmzxFgrCc9R in database.
D, [2021-09-24T08:49:43.025386 #29] DEBUG -- : [7226e315-5e56-4054-926e-6db23b697ec6] Meeting find_or_create: created=false on server_id=visio-bbb14.domain.fr (wanted visio-bbb15.domain.fr)
D, [2021-09-24T08:49:43.026595 #29] DEBUG -- : [7226e315-5e56-4054-926e-6db23b697ec6] Incrementing server visio-bbb14.domain.frload by 1
D, [2021-09-24T08:49:43.027376 #29] DEBUG -- : [7226e315-5e56-4054-926e-6db23b697ec6] Creating meeting REX3XkmzxFgrCc9R on BigBlueButton server visio-bbb14.domain.fr
D, [2021-09-24T08:49:43.028118 #14] DEBUG -- : [cbd25218-d688-4611-a6ee-8456f5c01cc5]    (0.4ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
D, [2021-09-24T08:49:43.029398 #14] DEBUG -- : [cbd25218-d688-4611-a6ee-8456f5c01cc5]   CACHE  (0.0ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
I, [2021-09-24T08:49:43.029490 #29]  INFO -- : [7226e315-5e56-4054-926e-6db23b697ec6] Completed 500 Internal Server Error in 8ms (ActiveRecord: 1.0ms | Allocations: 1447)
I, [2021-09-24T08:49:43.029801 #14]  INFO -- : [cbd25218-d688-4611-a6ee-8456f5c01cc5]   Rendering text template
I, [2021-09-24T08:49:43.029886 #14]  INFO -- : [cbd25218-d688-4611-a6ee-8456f5c01cc5]   Rendered text template (Duration: 0.0ms | Allocations: 1)
I, [2021-09-24T08:49:43.030051 #14]  INFO -- : [cbd25218-d688-4611-a6ee-8456f5c01cc5] Completed 200 OK in 6ms (Views: 0.4ms | ActiveRecord: 1.7ms | Allocations: 662)
F, [2021-09-24T08:49:43.030461 #29] FATAL -- : [7226e315-5e56-4054-926e-6db23b697ec6]   
[7226e315-5e56-4054-926e-6db23b697ec6] ActiveRecord::StatementInvalid (PG::UndefinedTable: ERREUR:  la relation « callback_data » n'existe pas
LINE 8:  WHERE a.attrelid = '"callback_data"'::regclass
                            ^
):
[7226e315-5e56-4054-926e-6db23b697ec6]   
[7226e315-5e56-4054-926e-6db23b697ec6] app/handlers/recording_ready_event_handler.rb:18:in `handle'
[7226e315-5e56-4054-926e-6db23b697ec6] app/handlers/event_handler.rb:13:in `handle'
[7226e315-5e56-4054-926e-6db23b697ec6] app/controllers/bigbluebutton_api_controller.rb:178:in `create'
```

WARNING: I anonymized some datas

**Additional context**
Scalelite version is 1.1.8 (tested with scalelite 1.1.7.1 also)

**Comment by jgribonvald** [comment]
Sorry, I've found the problem, the rake db:migrate wasn't applied on scalelite. `docker exec -t scalelite-api bundle exec rake db:migrate`

**Comment by sualko** [comment]
Thanks for providing the fix :clap:
